apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alexbissessur
  namespace: argocd
spec:
  destination:
    namespace: alexbissessur
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/applications/alexbissessur
    repoURL: https://github.com/xelab04/hopeops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
