apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama
  namespace: argocd
spec:
  destination:
    namespace: ollama
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideAppy=true
  sources:
    - repoURL: https://github.com/xelab04/hopeops.git
      targetRevision: main
      ref: values

    - chart: ollama
      repoURL: https://helm.otwld.com/
      targetRevision: 1.35.0
      helm:
        releaseName: ollama
        valueFiles:
          - $values/manifests/applications/ollama/values.yaml
        ignoreMissingValueFiles: true
