apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stump
  namespace: argocd
spec:
  destination:
    namespace: stump
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/applications/stump/
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideAppy=true
