apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tor-endpoint
  namespace: argocd
spec:
  destination:
    namespace: tor-endpoint
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kubernetes/
    repoURL: https://github.com/xelab04/tor-entrypoint.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideAppy=true
