apiVersion: v1
data:
  REGISTRY_AUTH: WVd4bGVEcHdZWE56ZDI5eVpBPT0=
  REGISTRY_URL: aHR0cHM6Ly9yZWdpc3RyeS5hbGV4Ymlzc2Vzc3VyLmRldg==
kind: Secret
metadata:
  name: registry-ui-secret
  namespace: docker-registry-ui

# kubectl create secret generic registry-ui-secret \
#   -n docker-registry-ui \
#   --from-literal=REGISTRY_URL="http://your-registry.com:5000" \
#   --from-literal=REGISTRY_AUTH="$(echo -n 'username:password' | base64)"
