# apiVersion: v1
# data:
#   ADMIN_PASSWORD:
#   ADMIN_USER:
#   AUTH_BACKEND:
#   DATABASE_DATABASE:
#   DATABASE_HOST:
#   DATABASE_PASSWORD:
#   DATABASE_PORT:
#   DATABASE_TYPE:
#   DATABASE_USER:
#   SECRET_KEY:
# kind: Secret
# metadata:
#   name: cot-env
# type: Opaque
