apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caddy
  namespace: argocd
spec:
  destination:
    namespace: caddy
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/caddy
    repoURL: https://github.com/xelab04/kates.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
