apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-config
data:
  config.json: |-
    {
      "repositories": ["xelab04/hopeops"],
      "kubernetes": {
        "managerFilePatterns": ["/\\.ya?ml$/"]
      },
      registryAliases: {
        "mirror.gcr.io": "docker.io",
      }
    }

#       "dryRun" : "full"
