apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: towonel-kraft
  name: towonel-kraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: towonel-kraft
  strategy: {}
  template:
    metadata:
      labels:
        app: towonel-kraft
    spec:
      containers:
      - image: git.erwanleboucher.dev/eleboucher/towonel-agent:latest
        name: towonel-agent
        resources: {}
        env:
          - name: TOWONEL_INVITE_TOKEN
            valueFrom:
              secretKeyRef:
                name: towonel-inv-key
                key: TOWONEL_KRAFT_TOKEN
          - name: TOWONEL_AGENT_SERVICES
            valueFrom:
              configMapKeyRef:
                name: towonel-hostnames
                key: TOWONEL_KRAFT_SERVICES

status: {}
