services:
  lk-jwt-service:
    image: ghcr.io/element-hq/lk-jwt-service:latest
    container_name: lk-jwt-service
    environment:
      - LIVEKIT_JWT_BIND=:8081
      - LIVEKIT_URL=wss://livekit.{DOMAIN}
      - LIVEKIT_FULL_ACCESS_HOMESERVERS={DOMAIN}
      - LIVEKIT_KEY=LK_MATRIX_KEY # APIUxUnMnSkuFWV
      - LIVEKIT_SECRET=LK_MATRIX_SECRET # t93ZVjPeoEdyx7Wbet3kG4L3NGZIZVEFvqe0UuiVc22A
    restart: unless-stopped
    ports:
      - "8081:8081"
    networks:
      - towonel-net

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit
    command: --config /etc/livekit.yaml
    restart: unless-stopped
    volumes:
      - /root/docker/livekit/livekit.yaml:/etc/livekit.yaml:ro
    # network_mode: "host" # /!\ LiveKit binds to all addresses by default.
    # Make sure port 7880 is blocked by your firewall to prevent access bypassing your reverse proxy
    # Alternatively, uncomment the lines below and comment `network_mode: "host"` above to specify port mappings.
    ports:
      - "127.0.0.1:7880:7880/tcp"
      - "7881:7881/tcp"
      - "50100-50200:50100-50200/udp"
    networks:
      - towonel-net

networks:
  towonel-net:
    name: towonel-shared
    external: true
