apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: gotosocial
  namespace: cnpg
spec:
  name: gotosocial
  owner: gotosocial
  cluster:
    name: main-postgres

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memtly
  namespace: cnpg
spec:
  name: memtly
  owner: memtly
  cluster:
    name: main-postgres

---

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: forgejo
  namespace: cnpg
spec:
  name: forgejo
  owner: forgejo
  cluster:
    name: main-postgres
