apiVersion: v1
kind: Secret
metadata:
  name: root-user-secret
  namespace: cnpg
type: Opaque
stringData:
  username: "root"
  password: "rootpassword"

---

apiVersion: v1
kind: Secret
metadata:
  name: gotosocial-db-password
  namespace: cnpg
type: Opaque
stringData:
  DB_DATABASE_NAME: gotosocial
  username: gotosocial
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: memtly-db-password
  namespace: cnpg
type: Opaque
stringData:
  DB_DATABASE_NAME: memtly
  username: memtly
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: kraft-db-password
  namespace: cnpg
type: Opaque
stringData:
  username: "kraftuser"
  password: "password"

---

apiVersion: v1
kind: Secret
metadata:
  name: forgejo-db-password
  namespace: cnpg
type: Opaque
stringData:
  username: "forgejo"
  password: "password"
