apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo/system/
    repoURL: https://github.com/xelab04/hopeops.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
      # prune: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideAppy=true
