additionalArguments:
  - "--entryPoints.kraft.address=:1337"
  - "--entryPoints.ssh.address=:24"
  # - "--certificatesresolvers.le.acme.email=alexbissessur@gmail.com"
  # - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  # - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  # - "--accesslog=true"
  # - "--accesslog.format=json"
  #- "--accesslog.fields.defaultmode=keep"
  #- "--accesslog.fields.headers.defaultmode=keep"
  - "--providers.kubernetescrd.allowEmptyServices=true"
  - "--providers.kubernetesingress.allowEmptyServices=true"
  - "--providers.kubernetesingress.ingressendpoint.publishedservice=traefik-system/traefik"

# dashboard:
#   enabled: true

logs:
  general:
    level: INFO

providers:
  kubernetesIngress:
    allowExternalNameServices: true
    # publishedService:
    #   enabled: true
    #   pathOverride: "traefik-system/traefik"

  kubernetesCRD:
    allowExternalNameServices: true

metrics:
  prometheus:
    enabled: true
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

ports:
  ssh:
    port: 24
    expose:
      default: true
    protocol: TCP
  kraft:
    port: 1337
    expose:
      default: true
    protocol: TCP

  web:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
    proxyProtocol:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"
  websecure:
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"
    proxyProtocol:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"

persistence:
  enabled: true
  name: "acme"
  accessMode: ReadWriteMany
  size: 128Mi
  path: /data

providers:
  kubernetesCRD:
    allowCrossNamespace: true

#certificatesResolvers:
#  le:
#    acme:
#      email: alexbissessur@gmail.com
#      storage: acme.json
#      httpChallenge:
#        entryPoint: web
