additionalArguments:
  - "--entryPoints.kraft.address=:1337"
  - "--entryPoints.ssh.address=:24"
  # - "--certificatesresolvers.le.acme.email=alexbissessur@gmail.com"
  # - "--certificatesresolvers.le.acme.storage=/data/acme.json"
  # - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
  - "--accesslog=true"
  - "--accesslog.format=json"
  #- "--accesslog.fields.defaultmode=keep"
  #- "--accesslog.fields.headers.defaultmode=keep"

# dashboard:
#   enabled: true

logs:
  general:
    level: INFO

# accesslog:
#   enabled: true
#   format: json

metrics:
  prometheus:
    enabled: true
    entryPoint: metrics
    addRoutersLabels: true
    addServicesLabels: true

ports:
  ssh:
    port: 24
    expose:
      default: true
    protocol: TCP
  kraft:
    port: 1337
    expose:
      default: true
    protocol: TCP

  web:
    transport:
      respondingTimeouts:
        readTimeout: "60s"
        writeTimeout: "60s"
        idleTimeout: "180s"
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
    proxyProtocol:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"
  websecure:
    transport:
      respondingTimeouts:
        readTimeout: "60s"
        writeTimeout: "60s"
        idleTimeout: "180s"
    forwardedHeaders:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"
    proxyProtocol:
      trustedIPs:
        - "10.42.0.0/16"
        - "127.0.0.1/32"
        - "192.168.0.0/24"

persistence:
  enabled: true
  name: "acme"
  accessMode: ReadWriteMany
  size: 128Mi
  path: /data

providers:
  kubernetesCRD:
    allowCrossNamespace: true
    allowEmptyServices: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: false
  kubernetesIngressNGINX:
    enabled: true
    controllerClass: traefik.io/ingress-controller
    ingressClass: traefik
    # allowExternalNameServices: true
    # allowEmptyServices: true
    # publishedService:
    #   enabled: true
    #   pathOverride: "traefik-system/traefik"
  kubernetesGateway:
    enabled: true
    experimentalChannel: true

    #certificatesResolvers:
#  le:
#    acme:
#      email: alexbissessur@gmail.com
#      storage: acme.json
#      httpChallenge:
#        entryPoint: web
